const { Component } = require("react");

module.exports = {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/introduction",
        "getting-started/core-concept",
        "getting-started/architecture",
        "install",
        "quick-start",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: false,
      items: [
        "tutorials/webservice",
        "tutorials/helm",
        "tutorials/consume-cloud-services",
        "tutorials/k8s-object",
        "tutorials/jenkins",
        "tutorials/trigger",
        "case-studies/gitops",
        "tutorials/workflows",
        // "case-studies/jenkins-cicd",
        // "case-studies/canary-blue-green",
      ],
    },
    {
      type: "category",
      label: "How-to Guides",
      collapsed: true,
      items: [
        // TODO:
        {
          type: "category",
          label: "VelaUX",
          collapsed: false,
          items: [
            {
              "Manage applications": [
                "how-to/dashboard/application/create-application",
                "how-to/dashboard/application/bind-new-environment",
                "how-to/dashboard/application/deploy-application",
                "how-to/dashboard/application/get-application-instance",
                "tutorials/scaler",
                "how-to/dashboard/application/get-application-log",
                "how-to/dashboard/application/get-application-endpoint",
                "how-to/dashboard/application/view-application-resource",
                "how-to/dashboard/application/get-application-revision",
                "how-to/dashboard/application/recycle-environment",
                "how-to/dashboard/application/delete-application",
              ],
            },
            {
              "Manage workflows": ["how-to/dashboard/workflow/overview"],
            },
            {
              "Manage traits": ["how-to/dashboard/trait/overview"],
            },
            {
              "Manage triggers": ["how-to/dashboard/trigger/overview"],
            },
            // {
            //   "Manage environment": ["how-to/dashboard/environment/overview"],
            // },
            {
              "Manage target": ["how-to/dashboard/target/overview"],
            },
            // {
            //   "Manage cluster": [
            //     "how-to/dashboard/cluster/overview",
            //     "how-to/dashboard/cluster/connect-cluster",
            //     "how-to/dashboard/cluster/detach-cluster",
            //     "how-to/dashboard/cluster/set-cluster-dashboard",
            //     "how-to/dashboard/cluster/edit-cluster",
            //   ],
            // },
            // {
            //   "Manage addon": ["how-to/dashboard/addon/overview"],
            // },
          ],
        },
        {
          type: "category",
          label: "CLI",
          collapsed: true,
          items: [
            "end-user/quick-start-cli",
            "end-user/traits/ingress",
            "end-user/components/cloud-services/provision-and-consume-cloud-services",
            "end-user/traits/rollout",
            "end-user/policies/health",
            "case-studies/multi-cluster",
            "end-user/workflow/component-dependency-parameter",
            "end-user/workflow/webhook-notification",
            "end-user/version-control",
            "how-to/cli/addon/addon",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Extension",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Learning OAM",
          collapsed: false,
          items: [
            "platform-engineers/oam/oam-model",
            "platform-engineers/oam/x-definition",
          ],
        },
        {
          "Learning CUE": [
            "platform-engineers/cue/basic",
            "platform-engineers/cue/definition-edit",
            "platform-engineers/cue/advanced",
          ],
        },
        "platform-engineers/addon/intro",
        "platform-engineers/components/custom-component",
        "platform-engineers/components/component-terraform",
        {
          type: "category",
          label: "Traits System",
          items: [
            "platform-engineers/traits/customize-trait",
            "platform-engineers/traits/patch-trait",
            "platform-engineers/traits/status",
            "platform-engineers/traits/advanced",
          ],
        },
        {
          "Workflow System": [
            "platform-engineers/workflow/workflow",
            "platform-engineers/workflow/cue-actions",
          ],
        },
        {
          "System Operation": [
            "platform-engineers/system-operation/bootstrap-parameters",
            "platform-engineers/system-operation/managing-clusters",
            "platform-engineers/system-operation/observability",
            "platform-engineers/system-operation/performance-finetuning",
            "platform-engineers/system-operation/velaql",
          ],
        },
        "platform-engineers/debug/dry-run",
        "platform-engineers/x-def-version",
      ],
    },
    {
      type: "category",
      label: "References",
      items: [
        "cli/vela",
        {
          type: "category",
          label: "Built-in Addons",
          items: [
              "reference/addons/overview",
              "reference/addons/velaux",
              "reference/addons/terraform",
          ],
        },
        {
          type: "category",
          label: "Supported Cloud Resource",
          items: [
            "end-user/components/cloud-services/terraform/alibaba-ack",
            "end-user/components/cloud-services/terraform/alibaba-amqp",
            "end-user/components/cloud-services/terraform/alibaba-ask",
            "end-user/components/cloud-services/terraform/alibaba-eip",
            "end-user/components/cloud-services/terraform/alibaba-mongodb",
            "end-user/components/cloud-services/terraform/alibaba-mse",
            "end-user/components/cloud-services/terraform/alibaba-oss",
            "end-user/components/cloud-services/terraform/alibaba-rds",
            "end-user/components/cloud-services/terraform/alibaba-redis",
            "end-user/components/cloud-services/terraform/alibaba-rocketmq",
            "end-user/components/cloud-services/terraform/alibaba-sls-project",
            "end-user/components/cloud-services/terraform/alibaba-sls-store",
            "end-user/components/cloud-services/terraform/alibaba-vpc",
            "end-user/components/cloud-services/terraform/alibaba-vswitch",
            "end-user/components/cloud-services/terraform/aws-acm",
            "end-user/components/cloud-services/terraform/aws-alb",
            "end-user/components/cloud-services/terraform/aws-autoscaling",
            "end-user/components/cloud-services/terraform/aws-bridgecrew-read-only",
            "end-user/components/cloud-services/terraform/aws-cloudfront-s3-cdn",
            "end-user/components/cloud-services/terraform/aws-cloudfront",
            "end-user/components/cloud-services/terraform/aws-cloudwatch-cis-alarms",
            "end-user/components/cloud-services/terraform/aws-cloudwatch-log-group",
            "end-user/components/cloud-services/terraform/aws-cloudwatch-log-metric-filter",
            "end-user/components/cloud-services/terraform/aws-cloudwatch-metric-alarm",
            "end-user/components/cloud-services/terraform/aws-cloudwatch-metric-alarms-by-multiple-dimensions",
            "end-user/components/cloud-services/terraform/aws-cloudwatch",
            "end-user/components/cloud-services/terraform/aws-config",
            "end-user/components/cloud-services/terraform/aws-dynamodb-table",
            "end-user/components/cloud-services/terraform/aws-ec2-instance",
            "end-user/components/cloud-services/terraform/aws-ecs-container-definition",
            "end-user/components/cloud-services/terraform/aws-ecs",
            "end-user/components/cloud-services/terraform/aws-eks-cluster-autoscaler",
            "end-user/components/cloud-services/terraform/aws-eks-external-dns",
            "end-user/components/cloud-services/terraform/aws-eks-kube-state-metrics",
            "end-user/components/cloud-services/terraform/aws-eks-node-problem-detector",
            "end-user/components/cloud-services/terraform/aws-eks",
            "end-user/components/cloud-services/terraform/aws-elasticache-redis",
            "end-user/components/cloud-services/terraform/aws-elb",
            "end-user/components/cloud-services/terraform/aws-guardduty",
            "end-user/components/cloud-services/terraform/aws-iam-account",
            "end-user/components/cloud-services/terraform/aws-iam-assumable-role-with-oidc",
            "end-user/components/cloud-services/terraform/aws-iam-assumable-role-with-saml",
            "end-user/components/cloud-services/terraform/aws-iam-assumable-role",
            "end-user/components/cloud-services/terraform/aws-iam-assumable-roles-with-saml",
            "end-user/components/cloud-services/terraform/aws-iam-assumable-roles",
            "end-user/components/cloud-services/terraform/aws-iam-eks-role",
            "end-user/components/cloud-services/terraform/aws-iam-group-with-assumable-roles-policy",
            "end-user/components/cloud-services/terraform/aws-iam-group-with-policies",
            "end-user/components/cloud-services/terraform/aws-iam-nofile",
            "end-user/components/cloud-services/terraform/aws-iam-policy-document-aggregator",
            "end-user/components/cloud-services/terraform/aws-iam-policy",
            "end-user/components/cloud-services/terraform/aws-iam-read-only-policy",
            "end-user/components/cloud-services/terraform/aws-iam-role",
            "end-user/components/cloud-services/terraform/aws-iam-s3-user",
            "end-user/components/cloud-services/terraform/aws-iam-system-user",
            "end-user/components/cloud-services/terraform/aws-iam-user",
            "end-user/components/cloud-services/terraform/aws-key-pair",
            "end-user/components/cloud-services/terraform/aws-kms-key",
            "end-user/components/cloud-services/terraform/aws-lambda-do-it-all",
            "end-user/components/cloud-services/terraform/aws-lambda-with-inline-code",
            "end-user/components/cloud-services/terraform/aws-lambda",
            "end-user/components/cloud-services/terraform/aws-notify-slack",
            "end-user/components/cloud-services/terraform/aws-rds-aurora",
            "end-user/components/cloud-services/terraform/aws-rds",
            "end-user/components/cloud-services/terraform/aws-route53-alias",
            "end-user/components/cloud-services/terraform/aws-route53-cluster-hostname",
            "end-user/components/cloud-services/terraform/aws-route53-delegation-sets",
            "end-user/components/cloud-services/terraform/aws-route53-records",
            "end-user/components/cloud-services/terraform/aws-route53-zones",
            "end-user/components/cloud-services/terraform/aws-route53",
            "end-user/components/cloud-services/terraform/aws-s3-log-storage",
            "end-user/components/cloud-services/terraform/aws-s3",
            "end-user/components/cloud-services/terraform/aws-secretsmanager-for-rollbar-access-tokens",
            "end-user/components/cloud-services/terraform/aws-security-group",
            "end-user/components/cloud-services/terraform/aws-security-hub",
            "end-user/components/cloud-services/terraform/aws-sns-topic",
            "end-user/components/cloud-services/terraform/aws-sqs",
            "end-user/components/cloud-services/terraform/aws-ssm-parameter-store",
            "end-user/components/cloud-services/terraform/aws-subnet",
            "end-user/components/cloud-services/terraform/aws-utils",
            "end-user/components/cloud-services/terraform/aws-vpc",
            "end-user/components/cloud-services/terraform/azure-database-mariadb",
            "end-user/components/cloud-services/terraform/azure-resource-group",
            "end-user/components/cloud-services/terraform/azure-storage-account",
            "end-user/components/cloud-services/terraform/azure-subnet",
            "end-user/components/cloud-services/terraform/azure-virtual-network",
            "end-user/components/cloud-services/terraform/tencent-subnet",
            "end-user/components/cloud-services/terraform/tencent-vpc",

          ],
        },
        {
          type: "category",
          label: "Built-in Component Type",
          items: [
            "end-user/components/helm",
            "end-user/components/cue/webservice",
            "end-user/components/cue/worker",
            "end-user/components/cue/task",
            "end-user/components/kustomize",
            "end-user/components/cue/raw",
            "end-user/components/more",
          ],
        },
        {
          type: "category",
          label: "Built-in Trait Type",
          items: [
            "end-user/traits/scaler",
            "end-user/traits/ingress",
            "end-user/traits/storage",
            "end-user/traits/rollout",
            "end-user/traits/annotations-and-labels",
            "end-user/traits/service-binding",
            "end-user/traits/sidecar",
            "end-user/traits/autoscaler",
            "end-user/traits/kustomize-patch",
            "end-user/traits/more",
          ],
        },
        {
          type: "category",
          label: "Built-in Policy Type",
          items: ["end-user/policies/envbinding"],
        },
        "end-user/workflow/built-in-workflow-defs",
        "reference/ui-schema",
        "reference/user-improvement-plan",
      ],
    },
    {
      type: "category",
      label: "Roadmap",
      items: ["roadmap/README"],
    },
    {
      type: "doc",
      id: "developers/references/devex/faq",
    },
  ],
};
