apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: my-component
      type: my-stateful
      properties:
        image: nginx:latest
        replicas: 1
        name: my-component
      traits:
      - type: sidecar
        properties:
          name: my-sidecar
          image: saravak/fluentd:elastic

